### ISSUE TITLE
Solid project and great meeting you!

### ISSUE THREAD

**Issue by puttputt** [cwilson58/ENSE-Capstone#18]
Hey guys,

We met briefly at project day and thought your project was absolutely outstanding. The 'polish' is what really set it apart.

I also got really good vibes from all of you, and you're the type of people that would fit in well at my company.

We're [Offstreet](https://joinoffstreet.com), a Regina-based startup building SaaS software for the transportation industry (mostly Universities at the moment). We have a team of 15 people and plan to add another 5-10 before the end of the year.

We're not actively hiring for dev roles at the moment, but we'd make an exception for a good fit.

Our tech stack is mostly web/typescript. Front-end apps in Angular, Svelte and React (our main app is currently an Angular/React hybrid as we migrate to React), back-end node.js on various AWS services.

![image](https://github.com/cwilson58/ENSE-Capstone/assets/27674/9892570b-4c00-474a-be92-33ad3a0d33eb)
This is just a little milestone we celebrated internally, without context the numbers don't really mean much, but I think it demonstrates that we are legit (we have about 100k MAUs and growing).

**My ask from you today is if I could get your contact information** (send me an email kyle@joinoffstreet.com), or add me on [LinkedIn](https://www.linkedin.com/in/kylesmyth/) if it's easier. I'm decently connected in the SK-technology ecosystem so if there's a tech company in the province you want an intro to I can totally make that happen.

If you're interested in going down the full-stack web-dev path, we have an always open job posting to collect resume's: https://offstreet.bamboohr.com/careers/24

Finally,
I graduated SSE back in 2013 and this was my capstone:
https://youtu.be/ZkzCLB0mR6c
It's a bit dated, but to be fair it was 11 years ago and Unity was still a young engine and assets were sparse. I wrote the gameserver (in python) because Unity didn't have built-in multiplayer support at the time. I'm still a gamedev hobbyist in my spare time, but I've dedicated my time to Unreal Engine these days.

Good luck with finals, you're almost done!

**Comment by cwilson58** [comment]
Thank you for reaching out! Contact info has been passed off to the team!
